In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [6]:
data=pd.read_csv('CarPrice_Assignment.csv')

In [7]:
data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [9]:
data.shape

(205, 26)

In [10]:
data.describe()

car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878   
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522   
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000   
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000   
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000   
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000   
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000   

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000   
mean   2555.565854  126.907317    3.329756    3.255415         10.142537   
std     520.680204   41.642693    0.270844    0.313597          3.972040   
min    1488.000000   61.000000    2.540000    2.070000          7.000000   
25%    2145.000000   97.000000    3.150000    3.110000          8.600000   
50%    2414.000000  120.000000    3.310000    3.290000          9.000000   
75%    2935.000000  141.000000    3.580000    3.410000          9.400000   
max    4066.000000  326.000000    3.940000    4.170000         23.000000   

       horsepower      peakrpm     citympg  highwaympg         price  
count  205.000000   205.000000  205.000000  205.000000    205.000000  
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571  
std     39.544167   476.985643    6.542142    6.886443   7988.852332  
min     48.000000  4150.000000   13.000000   16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000  
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000  
max    288.000000  6600.000000   49.000000   54.000000  45400.000000

In [11]:
encoder=LabelEncoder()
data['CarName']= encoder.fit_transform(data['CarName'])
CarName= {index: label for index, label in enumerate(encoder.classes_)}
CarName

{0: 'Nissan versa',
 1: 'alfa-romero Quadrifoglio',
 2: 'alfa-romero giulia',
 3: 'alfa-romero stelvio',
 4: 'audi 100 ls',
 5: 'audi 100ls',
 6: 'audi 4000',
 7: 'audi 5000',
 8: 'audi 5000s (diesel)',
 9: 'audi fox',
 10: 'bmw 320i',
 11: 'bmw x1',
 12: 'bmw x3',
 13: 'bmw x4',
 14: 'bmw x5',
 15: 'bmw z4',
 16: 'buick century',
 17: 'buick century luxus (sw)',
 18: 'buick century special',
 19: 'buick electra 225 custom',
 20: 'buick opel isuzu deluxe',
 21: 'buick regal sport coupe (turbo)',
 22: 'buick skyhawk',
 23: 'buick skylark',
 24: 'chevrolet impala',
 25: 'chevrolet monte carlo',
 26: 'chevrolet vega 2300',
 27: 'dodge challenger se',
 28: 'dodge colt (sw)',
 29: 'dodge colt hardtop',
 30: 'dodge coronet custom',
 31: 'dodge coronet custom (sw)',
 32: 'dodge d200',
 33: 'dodge dart custom',
 34: 'dodge monaco (sw)',
 35: 'dodge rampage',
 36: 'honda accord',
 37: 'honda accord cvcc',
 38: 'honda accord lx',
 39: 'honda civic',
 40: 'honda civic (auto)',
 41: 'honda civic 1

In [12]:
data['fueltype'] = encoder.fit_transform(data['fueltype'])
fueltype = {index : label for index, label in enumerate(encoder.classes_)}
fueltype

{0: 'diesel', 1: 'gas'}

In [13]:
data['aspiration'] = encoder.fit_transform(data['aspiration'])
aspiration = {index : label for index, label in enumerate(encoder.classes_)}
aspiration

{0: 'std', 1: 'turbo'}

In [14]:
data['doornumber'] = encoder.fit_transform(data['doornumber'])
doornumber = {index : label for index, label in enumerate(encoder.classes_)}
doornumber

{0: 'four', 1: 'two'}

In [15]:
data['carbody'] = encoder.fit_transform(data['carbody'])
carbody = {index : label for index, label in enumerate(encoder.classes_)}
carbody

{0: 'convertible', 1: 'hardtop', 2: 'hatchback', 3: 'sedan', 4: 'wagon'}

In [16]:
data['drivewheel'] = encoder.fit_transform(data['drivewheel'])
drivewheel = {index : label for index, label in enumerate(encoder.classes_)}
drivewheel

{0: '4wd', 1: 'fwd', 2: 'rwd'}

In [17]:
data['enginelocation'] = encoder.fit_transform(data['enginelocation'])
enginelocation = {index : label for index, label in enumerate(encoder.classes_)}
enginelocation

{0: 'front', 1: 'rear'}

In [18]:
data['enginetype'] = encoder.fit_transform(data['enginetype'])
enginetype = {index : label for index, label in enumerate(encoder.classes_)}
enginetype

{0: 'dohc', 1: 'dohcv', 2: 'l', 3: 'ohc', 4: 'ohcf', 5: 'ohcv', 6: 'rotor'}

In [19]:
data['cylindernumber'] = encoder.fit_transform(data['cylindernumber'])
cylindernumber = {index : label for index, label in enumerate(encoder.classes_)}
cylindernumber

{0: 'eight', 1: 'five', 2: 'four', 3: 'six', 4: 'three', 5: 'twelve', 6: 'two'}

In [20]:
data['fuelsystem'] = encoder.fit_transform(data['fuelsystem'])
fuelsystem = {index : label for index, label in enumerate(encoder.classes_)}
fuelsystem

{0: '1bbl',
 1: '2bbl',
 2: '4bbl',
 3: 'idi',
 4: 'mfi',
 5: 'mpfi',
 6: 'spdi',
 7: 'spfi'}

In [23]:
x=data.drop('price', axis=1)
y=data['price']

In [24]:
scaler=MinMaxScaler(copy=True, feature_range=(0,1))
X=scaler.fit_transform(x)
print('x \n' , X[:206])
print('y \n' , y[:206])

x 
 [[0.         1.         0.01369863 ... 0.34693878 0.22222222 0.28947368]
 [0.00490196 1.         0.02054795 ... 0.34693878 0.22222222 0.28947368]
 [0.00980392 0.6        0.00684932 ... 0.34693878 0.16666667 0.26315789]
 ...
 [0.99019608 0.2        0.95890411 ... 0.55102041 0.13888889 0.18421053]
 [0.99509804 0.2        0.97260274 ... 0.26530612 0.36111111 0.28947368]
 [1.         0.2        0.97945205 ... 0.51020408 0.16666667 0.23684211]]
y 
 0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...   
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64


In [28]:
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=30 ,random_state=0)

In [30]:
print("X-train shape is :", x_train.shape)

X-train shape is : (175, 25)


In [32]:
print("X-test shape is :", x_test.shape)

X-test shape is : (30, 25)


In [33]:
print("Y-train shape is :", y_train.shape)

Y-train shape is : (175,)


In [34]:
print("Y-test shape is :", y_test.shape)

Y-test shape is : (30,)


In [35]:
DecisionTreeRegressorModel=DecisionTreeRegressor(max_depth=5, random_state=33)
DecisionTreeRegressorModel.fit(x_train, y_train)
print("DecisionTreeRegressor Train score is: ", DecisionTreeRegressorModel.score(x_train, y_train))
print("DecisionTreeRegressor Test score is: ", DecisionTreeRegressorModel.score(x_test, y_test))

DecisionTreeRegressor Train score is:  0.9730170115084147
DecisionTreeRegressor Test score is:  0.8421309794013154


In [37]:
y_predict=DecisionTreeRegressorModel.predict(x_test)
print('Predicted Value for DecisionTreeRegressorModel is : ' , y_predict[:206])

Predicted Value for DecisionTreeRegressorModel is :  [ 6123.125      15558.5104375  13950.          6123.125
  9575.70588235 15558.5104375   6123.125       7208.25
 15558.5104375   6123.125      19476.1        34833.77777778
 13711.66666667 14561.57894737  7208.25       15558.5104375
 14561.57894737 17710.          7790.21875     6123.125
  9575.70588235 14561.57894737  9575.70588235 15558.5104375
 15558.5104375   7790.21875     7790.21875    14561.57894737
  7790.21875     7790.21875   ]


In [38]:
RandomForestRegressorModel = RandomForestRegressor(n_estimators=100,max_depth=11, random_state=33)
RandomForestRegressorModel.fit(x_train, y_train)

print('Random Forest Regressor Train Score is : ' , RandomForestRegressorModel.score(x_train, y_train))
print('Random Forest Regressor Test Score is : ' , RandomForestRegressorModel.score(x_test, y_test))
print('Random Forest Regressor No. of features are : ' , RandomForestRegressorModel.n_features_)
print('----------------------------------------------------')

y_pred = RandomForestRegressorModel.predict(x_test)
print('Predicted Value for Random Forest Regressor is : ' , y_pred[:10])

Random Forest Regressor Train Score is :  0.9902196358021049
Random Forest Regressor Test Score is :  0.8962816585441333
Random Forest Regressor No. of features are :  25
----------------------------------------------------
Predicted Value for Random Forest Regressor is :  [ 5976.14516667 16485.88941667 14478.915       5908.45
  9955.61470238 14229.31729167  5951.056       7636.78301587
 18419.43334     6749.74585714]


In [39]:
MSEValue = mean_squared_error(y_test, y_pred, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

Mean Squared Error Value is :  3525489.5043689557
